### ISSUE TITLE
Tiny beautiful change in the Labels´ definition :)

### ISSUE THREAD

**Issue by HeikkiDev** [edgarfgp/WeatherAppXF#2]
I propose to change the horizontal Stacklayouts by single Label with StringFormat:

`<StackLayout Orientation="Horizontal">
            <Label Text="Description :" />
            <Label Text="{Binding WeatherInfo.Description}" />
</StackLayout>`

to:

`
<Label Text="{Binding WeatherInfo.Description, StringFormat='Description: {0}'}"/>
`

**Comment by AchrafKadiri** [comment]
Feel free to fork our project and edit it. Thanks for the improvement Enrique!! See you :)
